# Generated by Django 5.0.6 on 2024-05-22 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star_given',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
